# Generated by Django 4.1.7 on 2023-06-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_abc_app', '0018_alter_abc_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Известен год. Определить, будет ли этот год високосным, и к какому веку этот год относится.', max_length=255, verbose_name='Формулировка  задачи')),
                ('year', models.IntegerField()),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения(save)')),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
                'ordering': ('-id', '-year'),
            },
        ),
        migrations.DeleteModel(
            name='Abc',
        ),
    ]
